/*
 * Fabric CA
 * Specification for REST API Fabric CA
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FabricCa);
  }
}(this, function(expect, FabricCa) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FabricCa.AdminApi();
  });

  describe('(package)', function() {
    describe('AdminApi', function() {
      describe('changeUserStatus', function() {
        it('should call changeUserStatus successfully', function(done) {
          // TODO: uncomment, update parameter values for changeUserStatus call
          /*
          var username = "username_example";
          var status = "status_example";

          instance.changeUserStatus(username, status, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteUser', function() {
        it('should call deleteUser successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteUser call
          /*
          var username = "username_example";

          instance.deleteUser(username, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getApprovalList', function() {
        it('should call getApprovalList successfully', function(done) {
          // TODO: uncomment getApprovalList call
          /*

          instance.getApprovalList(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
